# Generated by Django 4.1.2 on 2022-10-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_1', models.BooleanField(blank=True, default=False, null=True)),
                ('status_2', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='users', to='users.player')),
            ],
        ),
    ]
